### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by atharvatp** [natesales/pathvector#217]
Hello, I have a problem after apt update & apt upgrade and Pathvector can't generate. Using the latest Debian 12.

```
Operating System: Debian GNU/Linux 12 (bookworm)
Kernel: Linux 6.1.0-17-amd64
Architecture: x86-64
```

```
pathvector version
Pathvector 6.3.2
Built c35220bf121f366ff05a51d93c6236e8c324d682 on 2023-06-11T07:03:14Z
No plugins
BIRD: ready.
```

```
pathvector g -t
INFO[0000] Starting Pathvector 6.3.2
DEBU[0000] Loading config from /etc/pathvector.yml
DEBU[0000] Setting PeeringDB endpoint to https://peeringdb.com/api/
DEBU[0000] Adding ASN to blocklist: 964
DEBU[0000] Adding ASN to blocklist: 3855
DEBU[0000] Adding ASN to blocklist: 4134
DEBU[0000] Adding ASN to blocklist: 4837
DEBU[0000] Adding ASN to blocklist: 8643
DEBU[0000] Adding ASN to blocklist: 9498
DEBU[0000] Adding ASN to blocklist: 12389
DEBU[0000] Adding ASN to blocklist: 12618
DEBU[0000] Adding ASN to blocklist: 13194
DEBU[0000] Adding ASN to blocklist: 14828
DEBU[0000] Adding ASN to blocklist: 24560
DEBU[0000] Adding ASN to blocklist: 27983
DEBU[0000] Adding ASN to blocklist: 31083
DEBU[0000] Adding ASN to blocklist: 34139
DEBU[0000] Adding ASN to blocklist: 46690
DEBU[0000] Adding ASN to blocklist: 42910
DEBU[0000] Adding ASN to blocklist: 43849
DEBU[0000] Adding ASN to blocklist: 47155
DEBU[0000] Adding ASN to blocklist: 48854
DEBU[0000] Adding ASN to blocklist: 51167
DEBU[0000] Adding ASN to blocklist: 51375
DEBU[0000] Adding ASN to blocklist: 52531
DEBU[0000] Adding ASN to blocklist: 56044
DEBU[0000] Adding ASN to blocklist: 60631
DEBU[0000] Adding ASN to blocklist: 141921
DEBU[0000] Adding ASN to blocklist: 151544
DEBU[0000] Adding ASN to blocklist: 197784
DEBU[0000] Adding ASN to blocklist: 199524
DEBU[0000] Adding ASN to blocklist: 202376
DEBU[0000] Adding ASN to blocklist: 205081
DEBU[0000] Adding ASN to blocklist: 206119
DEBU[0000] Loaded 31 ASNs and 0 prefixes into global blocklist
DEBU[0000] Finished loading config
DEBU[0000] Loading templates from embedded filesystem
DEBU[0000] Finished loading templates
DEBU[0000] Making cache directory /var/run/pathvector/cache/
DEBU[0000] Creating global config
DEBU[0000] Finished creating global config file
DEBU[0000] Writing global config file
DEBU[0000] Finished writing global config file
DEBU[0000] Processing peers
DEBU[0000] Processing ASxxx xxx_Downstream
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7d6ca0]

goroutine 86 [running]:
github.com/natesales/pathvector/pkg/process.peer({0xc000022a10, 0x10}, 0xc000781800, 0xc00051e480, 0x0?)
        /home/runner/work/pathvector/pathvector/pkg/process/process.go:677 +0x2a0
created by github.com/natesales/pathvector/pkg/process.Run
        /home/runner/work/pathvector/pathvector/pkg/process/process.go:818 +0xc59
```

How to solve this?

Thanks

**Comment by natesales** [comment]
Can I see your config? Feel free to redact with `pathvector config --sanitize`
